### ISSUE TITLE
PHP8支持

### ISSUE THREAD

**Issue by Andy17269** [2Broear/2BLOG#1]
我在PHP8.0中启用本主题出现了许多的问题，包括在主页上。能否支持PHP8。个人感觉这款主题很好看

**Comment by 2Broear** [comment]
> 我在PHP8.0中启用本主题出现了许多的问题，包括在主页上。能否支持PHP8。个人感觉这款主题很好看

我这边只测试过 5.6 和 7.3，首页具体是什么报错呢（[有录过视频流程](https://www.bilibili.com/video/BV1ig411C7FH)

**Comment by Andy17269** [comment]
![image](https://user-images.githubusercontent.com/81066358/187010859-7ee47666-dc05-431d-8f6a-35f00b8dbb87.png)
PHP8

**Comment by Andy17269** [comment]
Wordpress6.0.1

**Comment by 2Broear** [comment]
已更新PHP8.0支持到v1.3.x版本 @Andy17269
