### ISSUE TITLE
请问博主可以提供主题下载嘛？

### ISSUE THREAD

**Issue by martixtexworld** [2Broear/2BLOG#2]
意外发现这个wp主题，看了博主的站点，设计得很清爽，也很实用。整体感觉非常不错。谢谢大佬！

**Comment by 2Broear** [comment]
> 

客气了，有问题欢迎反馈

**Comment by 2Broear** [comment]
> 意外发现这个wp主题，看了博主的站点，设计得很清爽，也很实用。整体感觉非常不错。谢谢大佬！

客气了，有问题欢迎反馈
