### ISSUE TITLE
请问能添加萌备吗？[更新twikoo版本,已解决]

### ISSUE THREAD

**Issue by kuheg** [2Broear/2BLOG#4]
没有找到方法
看到了，<script src="https://cdn.staticfile.org/twikoo/1.6.4/twikoo.all.min.js"></script>
很棒的主题！特别是能支持第三方评论系统。以为要自食其力，后来发现居然有主题原生支持。
请问怎么更新twikoo版本，最新版1.6.31支持CF的Turnstile人机验证,

**Comment by kuheg** [comment]
一个不算问题的情况，我发现好像PHP8.0还是不支持，
切换到PHP7.4之后就没有报错了。使用PHP8.0会有报错，不知道怎么回事。

**Comment by kuheg** [comment]
尬尴找到了，居然在页脚。在评论，插件，主题等等没找到

**Comment by 2Broear** [comment]
> 尬尴找到了，居然在页脚。在评论，插件，主题等等没找到 在页脚打算修改成萌备发现了 请问能添加一个萌备吗？ 关于萌备：https://icp.gov.moe/AboutMoeICP.html 萌备-异次元之旅：https://travel.moe/ 跟十年之约类似

萌备已经添加到最新主题控件了哦 @kuheg 。另外 php8 的报错，具体是什么样的呢（位置，信息），我这边测试了没问题
